if(DEFINED _LLVM_CLANG_CMAKE_LOADED)
  return()
endif()
set(_LLVM_CLANG_CMAKE_LOADED TRUE)

if(DEFINED LLVM_PREFIX AND NOT DEFINED ENV{LLVM_PREFIX})
  set(_llvm_bin "${LLVM_PREFIX}/bin")
elseif(DEFINED ENV{LLVM_PREFIX})
  set(_llvm_bin "$ENV{LLVM_PREFIX}/bin")
elseif(EXISTS "/opt/homebrew/opt/llvm/bin/clang")
  set(_llvm_bin "/opt/homebrew/opt/llvm/bin")
elseif(EXISTS "/usr/local/opt/llvm/bin/clang")
  set(_llvm_bin "/usr/local/opt/llvm/bin")
endif()

if(_llvm_bin)
  # Toolchain files run before project(), so CMAKE_EXECUTABLE_SUFFIX isn't available yet.
  set(_exe_suffix "")
  if(CMAKE_HOST_WIN32)
    set(_exe_suffix ".exe")
    set(CMAKE_RC_COMPILER "${_llvm_bin}/llvm-rc${_exe_suffix}" CACHE FILEPATH "Resource compiler")
  endif()

  set(CMAKE_C_COMPILER      "${_llvm_bin}/clang${_exe_suffix}"   CACHE FILEPATH "C compiler")
  set(CMAKE_CXX_COMPILER    "${_llvm_bin}/clang++${_exe_suffix}" CACHE FILEPATH "C++ compiler")
  set(CMAKE_OBJC_COMPILER   "${_llvm_bin}/clang${_exe_suffix}"   CACHE FILEPATH "Objective-C compiler")
  set(CMAKE_OBJCXX_COMPILER "${_llvm_bin}/clang++${_exe_suffix}" CACHE FILEPATH "Objective-C++ compiler")
  message(STATUS "LLVM toolchain: ${_llvm_bin}")
endif()
